#!/bin/bash
#
# Add MediaConfig File
#

set -euo pipefail

LOGLEVEL=${LOG_LEVEL:-info}

yq -i ".authHTTPAddress = \"$API_URL/api/video/auth\"" /mediamtx.yml
yq -i ".logLevel = \"$LOGLEVEL\"" /mediamtx.yml

npx tsx index.ts &

/mediamtx /mediamtx.yml