services:
  mediamtx:
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    build: .
    restart: always
    environment:
      - API_URL
    ports:
      - 8554:8554
      - 9997:9997
      - 8889:8889
      - 8189:8189
      - 8189:8189/udp
