#!/bin/sh
#
# Add MediaConfig File
#

set -eu

LOGLEVEL=${LOG_LEVEL:-info}

AUTH_ADDRESS="http://127.0.0.1:9997/auth"

if [ "${CLOUDTAK_Mode:-}" = "docker-compose" ] && printf '%s' "$API_URL" | grep -q 'localhost'; then
  API_URL=$(printf '%s' "$API_URL" | sed 's/localhost/api/')
  export API_URL
fi

sed -i "s|^authHTTPAddress: .*|authHTTPAddress: ${AUTH_ADDRESS}|" /mediamtx.yml
sed -i "s|^logLevel: .*|logLevel: ${LOGLEVEL}|" /mediamtx.yml

node /dist/index.js &

exec /mediamtx /mediamtx.yml
